# Purpose: Generate the tables and figure for the FRED-MD financial
# application (Section 4.5) from the Phase-1 scan results.
library(ggplot2)

d <- read.csv("results/fredmd/phase1_h1_summary.csv", stringsAsFactors = FALSE)
d$group_code <- factor(d$group, levels = c("Prices", "Rate", "Spread", "FX"))

group_label <- c(
  Prices = "Prices", Rate = "Interest rates",
  Spread = "Credit/term spreads", FX = "Exchange rates"
)
group_label_wrap <- c(
  Prices = "Prices", Rate = "Interest\nrates",
  Spread = "Credit/term\nspreads", FX = "Exchange\nrates"
)
d$group <- group_label[as.character(d$group_code)]
d <- d[order(d$group_code, d$rmse_ratio), ]

# --- full 41-row appendix table ---
rows <- character(0)
for (i in seq_len(nrow(d))) {
  rows <- c(rows, sprintf(
    "%s & %s & %.3f & %.3f \\\\",
    gsub("_", "\\\\_", d$id[i]), d$group[i],
    d$rmse_ratio[i], d$mae_ratio[i]
  ))
}

appendix_tex <- c(
  "% latex table generated by src/analysis/fredmd_analysis.R",
  "\\begin{table}[ht]",
  "\\centering",
  "\\begingroup\\scriptsize",
  "\\begin{tabular}{llrr}",
  "\\toprule",
  "\\textbf{Series} & \\textbf{Group} & \\textbf{RMSE ratio} & \\textbf{MAE ratio} \\\\",
  "\\midrule",
  rows,
  "\\bottomrule",
  "\\end{tabular}",
  "\\endgroup",
  "\\caption{RMSE and MAE ratios \\eqref{eq:rmse-rat-fredmd} of the hedged random forest relative to the standard random forest for all 41 FRED-MD target series, horizon $h=1$, 432 out-of-sample months (1990-05--2026-04).}",
  "\\label{tab:fredmd-detail}",
  "\\end{table}"
)
writeLines(appendix_tex, "paper/hedged_random_forest/tables/fredmd_rmse_ratios.tex")

# --- compact summary table for the main body ---
agg <- do.call(rbind, lapply(split(d, d$group_code), function(s) {
  data.frame(
    group = group_label[[as.character(s$group_code[1])]],
    n = nrow(s),
    mean_rmse = mean(s$rmse_ratio),
    median_rmse = median(s$rmse_ratio),
    share_below1 = 100 * mean(s$rmse_ratio < 1)
  )
}))
agg <- agg[match(group_label, agg$group), ]

summary_rows <- sprintf(
  "%s & %d & %.3f & %.3f & %.0f\\%% \\\\",
  agg$group, agg$n, agg$mean_rmse, agg$median_rmse, agg$share_below1
)

summary_tex <- c(
  "% latex table generated by src/analysis/fredmd_analysis.R",
  "\\begin{table}[ht]",
  "\\centering",
  "\\begin{tabular}{lrrrr}",
  "\\toprule",
  "\\textbf{Group} & \\textbf{$N$} & \\textbf{Mean ratio} & \\textbf{Median ratio} & \\textbf{Share ratio $<1$} \\\\",
  "\\midrule",
  summary_rows,
  "\\midrule",
  sprintf(
    "All series & %d & %.3f & %.3f & %.0f\\%% \\\\", nrow(d),
    mean(d$rmse_ratio), median(d$rmse_ratio), 100 * mean(d$rmse_ratio < 1)
  ),
  "\\bottomrule",
  "\\end{tabular}",
  "\\caption{RMSE ratios \\eqref{eq:rmse-rat-fredmd} of the hedged random forest relative to the standard random forest, by FRED-MD group, horizon $h=1$. \\emph{Share ratio $<1$} is the fraction of series within the group for which HRF achieves a lower RMSE than RF. Full per-series results are in Appendix~\\ref{sec:results-in-table-format}, Table~\\ref{tab:fredmd-detail}.}",
  "\\label{table:fredmd-summary}",
  "\\end{table}"
)
writeLines(summary_tex, "paper/hedged_random_forest/tables/fredmd_rmse_summary.tex")

cat(
  "wrote tables/fredmd_rmse_ratios.tex (", length(rows),
  "rows) and tables/fredmd_rmse_summary.tex\n"
)

# --- boxplot of RMSE ratios by group ---
d$group_wrap <- factor(group_label_wrap[as.character(d$group_code)],
  levels = c("Prices", "Interest\nrates", "Credit/term\nspreads", "Exchange\nrates")
)

plot <- ggplot(d, aes(x = group_wrap, y = rmse_ratio, fill = group_wrap)) +
  geom_boxplot() +
  theme_minimal() +
  theme(legend.position = "none") +
  labs(x = NULL, y = NULL) +
  geom_hline(yintercept = 1, linetype = "dashed", color = "red", linewidth = 0.15) +
  scale_y_continuous(limits = c(0.88, 1.03), minor_breaks = seq(0.88, 1.03, 0.02)) +
  stat_summary(fun = mean, geom = "point", shape = 23, size = 2, fill = "red")

ggsave("results/fredmd_rmse_ratios_boxplot.eps", plot,
  width = 6.01, height = 5, units = "in"
)
file.copy("results/fredmd_rmse_ratios_boxplot.eps",
  "paper/hedged_random_forest/graphs/fredmd_rmse_ratios_boxplot.eps",
  overwrite = TRUE
)
cat("wrote results/fredmd_rmse_ratios_boxplot.eps and graphs/fredmd_rmse_ratios_boxplot.eps\n")
